name: Update book list

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: git rm docs/*.html
    - run: mkdir -p docs
    - run: npm run main
    - run: npm run render
    - run: |
        git add docs/*.html search_cache.json
        git status
        if ! git diff --exit-code --quiet HEAD >/dev/null ; then
          git config --global user.email take-cheeze@users.noreply.github.com
          git config --global user.name "take-cheeze bot"
          git commit -m "Update book list"
          git push https://take-cheeze:{{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git master
        fi
